services:
  - type: web
    name: quizclash-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements-production.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: quizclash-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 10080
    healthCheckPath: /health

databases:
  - name: quizclash-db
    databaseName: quizclash
    user: quizclash_user
    plan: free
